AzureBlobProject/Models/Blob.cs
namespace AzureBlobProject.Models;

public class Blob
{
        public string Comment { get; set; }
        public string Title { get; set; }
        public string Uri { get; set; }
}

AzureBlobProject/Models/Container.cs
using System.ComponentModel.DataAnnotations;

namespace AzureBlobProject.Models;

public class Container
{
    [Required]
    public string Name { get; set; }
}

AzureBlobProject/Models/ErrorViewModel.cs
namespace AzureBlobProject.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AzureBlobProject/Controllers/BlobController.cs
using AzureBlobProject.Models;
using AzureBlobProject.Services;
using Microsoft.AspNetCore.Mvc;

namespace AzureBlobProject.Controllers;

public class BlobController : Controller
{
    private readonly IBlobService _blobService;

    public BlobController(IBlobService blobService)
    {
        _blobService = blobService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Manage(string containerName)
    {
        var blobObj = await _blobService.GetAllBlobs(containerName);
        
        return View(blobObj);
    }
    [HttpGet]
    public IActionResult AddFile(string containerName)
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> AddFile(string containerName,Blob blob, IFormFile file)
    {
        if (file == null || file.Length < 1) return View();

        var fileName = Path.GetFileNameWithoutExtension(file.FileName) + "_" + Guid.NewGuid() +
                       Path.GetExtension(file.FileName);
        var result = await _blobService.UploadBlob(fileName, file, containerName,blob);

        if (result)
            return RedirectToAction("Index", "Container");

        return View();
    }
    [HttpGet]
    public async Task<IActionResult> ViewFile(string name,string containerName)
    {
        return Redirect(await _blobService.GetBlob(name, containerName));
    }
    public async Task<IActionResult> DeleteFile(string name,string containerName)
    {
        await _blobService.DeleteBlob(name, containerName);
        
        return RedirectToAction("Index","Container");
    }
}

AzureBlobProject/Controllers/ContainerController.cs
using System.ComponentModel;
using AzureBlobProject.Services;
using Microsoft.AspNetCore.Mvc;
using AzureBlobProject.Models;
using Container = AzureBlobProject.Models.Container;

namespace AzureBlobProject.Controllers;

public class ContainerController : Controller
{
    private readonly IContainerService _containerService;

    public ContainerController(IContainerService containerService)
    {
        _containerService = containerService;
    }

    public async Task<IActionResult> Index()
    {
        var allContainer = await _containerService.GetAllContainer();

        return View(allContainer);
    }

    public async Task<IActionResult> Delete(string containerName)
    {
        await _containerService.DeleteContainer(containerName);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Create()
    {
        return View(new Container());
    }
    [HttpPost]
    public async Task<IActionResult> Create(Container container)
    { 
        await _containerService.CreateContainer(container.Name);
        return RedirectToAction(nameof(Index));
    }
    
}

AzureBlobProject/Controllers/HomeController.cs
using AzureBlobProject.Services;
using Microsoft.AspNetCore.Mvc;

namespace AzureBlobProject.Controllers;

public class HomeController : Controller
{
    
    private readonly IContainerService _containerService;
    private readonly IBlobService _blobService;
    public HomeController(IContainerService containerService,IBlobService blobService)
    {
        _containerService = containerService;
        _blobService = blobService;
    }

    // GET
    public async Task<IActionResult> Index()
    {
        return View(await _containerService.GetALlContainerAndBlobs());
    }
    public async Task<IActionResult> Images()
    {
        return View(await _blobService.GetAllBlobsWIthUri("privatecontainer"));
    }
}

AzureBlobProject/Views/Blob/AddFile.cshtml
@model Blob

<form method="post" asp-action="AddFile" asp-controller="Blob" enctype="multipart/form-data">
    <div class="container">
        <h3>
            <h3>Container Name - @Context.Request.Query["containerName"].ToString()</h3>
        </h3>
        <input hidden name="containerName" value="@Context.Request.Query["containerName"].ToString()" type="text">

        <div class="row border p-2">
            
            <div class="col-12 pb-2"><h4 class="text-primary">Add Item to Blob : </h4></div>
            <div class="col-2">
                Title
            </div>
            <div class="col-4">
                <input asp-for="Title" class="form-control pt-1"/>
            </div>

            <div class="col-2">
                Comments
            </div>
            <div class="col-4">
                <input asp-for="Comment" class="form-control pt-1"/>
            </div>

            <div class="col-2">
                Upload Blob
            </div>
         
            <div class="col-4 pt-3">
                <input type="file" class="form-control pt-1" name="file"/>
            </div>
            
            <div class="col-2 pt-3"></div>
            <div class="col-4 pt-3">
                <button type="submit" class="btn btn-success form-control">Add</button>
            </div>
            
        </div>
    </div>
</form>

AzureBlobProject/Views/Blob/Manage.cshtml
@model List<string>


<div class="container p-4 border">
    <div class="row">
        <div class="col-6">
            <h3>Container Name @Context.Request.Query["containerName"].ToString()</h3>
        </div>
        <div class="col-6 text-right">
            <a asp-action="AddFile" asp-controller="Blob" asp-route-containerName=@Context.Request.Query["containerName"].ToString() class="btn btn-success"> Add Blob</a>
        </div>
    </div>
    <div class="contaier pt-4">
        @foreach (var item in Model)
        {
            <div class="row py-1">
                <div class="col-6">
                    <a asp-action="ViewFile" asp-controller="Blob" target="_blank" asp-route-name="@item"
                       asp-route-containerName=@Context.Request.Query["containerName"].ToString()>
                        @item
                    </a>
                </div>
                <div class="col-6">
                    <a asp-action="DeleteFile" asp-controller="Blob" asp-route-name="@item"
                       asp-route-containerName=@Context.Request.Query["containerName"].ToString() class="btn btn-danger">Delete </a>
                </div>
            </div>
        }
    </div>
</div>

AzureBlobProject/Views/Container/Create.cshtml
 @model Container

<div class="container border p-3">
     <h2 class="text-info pb-2">Create Container</h2>
     <form method="post" asp-action="Create">
          <div class="backgroundWhite">
               <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group row">
                         <div class="col-2">
                              <label asp-for="Name" class="col-form-label"></label>
                         </div> 
                         <div class="col-5">
                              <input asp-for="Name" class="form-control"/>
                         </div>
                         <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                         <div class="col-6">
                              <input type="submit" class="btn btn-info form-control" value="Create"/>
                         </div>
                         <div class="col-6">
                              <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                         </div>
                    </div>
               </div>
      
     </form>
</div>
@section Scripts{
     @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AzureBlobProject/Views/Container/Index.cshtml
@model List<string>

<br />
<br />
<div class="border backgroundWhite p-4">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info"> Container List</h2>
        </div>
        <div class="col-6 text-right">
            
              <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp;  Create New </a>
        </div>
    </div>
    <br />
    <div>
        @if (Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        Container Name
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => item)
                        </td>
                        <td>
                            <a class="btn btn-danger text-white" asp-action="Manage" asp-controller="Blob" asp-route-containerName="@item">Manage</a>
                          
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-containerName="@item">Delete</a>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No category exists...</p>
        }
    </div>
</div>

AzureBlobProject/Views/Home/Images.cshtml
@model List<Blob>


<div class="p-4 container">
    <div class="row">
        <h4 class="text-primary"> Images</h4>
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-4 border p-2">
                <h4 class="text-success">@item.Title</h4>
                <img src="@item.Uri" width="100%"/>
            </div>
        }
    </div>
</div>

AzureBlobProject/Views/Home/Index.cshtml
@model List<string>


<div class="p-4">
    <h4 class="text-primary">Blob Storage Hierarchy</h4>
    
    @foreach (var item in Model)
    {
        <p>@item</p>
    }
</div>

AzureBlobProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - AzureBlobProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <!--- <link rel="stylesheet" href="~/AzureBlobProject.styles.css" asp-append-version="true"/>-->

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="Container" asp-action="Index">AzureBlobProject</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Images">Images</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="Container" asp-action="Index">Container</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - AzureBlobProject - <a asp-area="" asp-controller="Container" asp-action="Index">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>